inference_dir : '/Users/amohamed/dust/amohamed/HTC/graph_building/LUXETrackML/datasets_sampling_graph_bootstrap_30/valid'
n_inference : 10
run_dir: '/Users/amohamed/dust/amohamed/HTC/graph_building/LUXETrackML/GNN_training_sampling_wl1_reg_sgd_5perc/'
output_dir: '/Users/amohamed/dust/amohamed/HTC/graph_building/LUXETrackML/GNN_training_sampling_wl1_reg_sgd_5on30perc_predictions/'
gpu : '0'
n_thread : 48
hid_dim : 128
n_iters : 4
