inference_dir : '/home/amohamed/GPFS/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/datasets_sampling_graph_bootstrap_5/valid'
n_inference : 100
run_dir: '/home/amohamed/GPFS/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/GNN_training_sampling_wl1_reg_sgd_noreg_20perc/'
output_dir: '/home/amohamed/GPFS/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/GNN_training_sampling_wl1_reg_sgd_20on5perc_predictions/'
gpu : '0'
n_thread : 48
hid_dim : 128
n_iters : 4
