train_dir : '/nfs/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/datasets/train'
valid_dir : '/nfs/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/datasets/valid'
dataset : 'LUXE-TRACKING-FBX-7.0'
log_dir : '/nfs/dust/ilc/user/amohamed/HTC/graph_building/LUXETrackML/GNN_training/'
run_type : 'new_run'
gpu : '0'
n_files : 100
n_valid : 10
n_train : 90
lr_c : 0.001
batch_size : 1
n_iters : 4
n_epoch : 100
TEST_every : 90
hid_dim : 128
network : 'CNN'
optimizer : 'Adam'
loss_func : 'BinaryCrossentropy'
n_thread : 4
log_verbosity : 1