train_dir : '/Users/amohamed/ML/LUXETrackML/test_dataset/train'
valid_dir : '/Users/amohamed/ML/LUXETrackML/test_dataset/valid'
dataset : 'LUXE-TRACKING-5Perc'
log_dir : '/Users/amohamed/ML/LUXETrackML/test_local_training/'
run_type : 'continue'
gpu : '0'
n_files : 20
n_valid : 5
n_train : 10
lr_c : 0.001
batch_size : 5
n_iters : 4
n_epoch : 11
TEST_every : 1
hid_dim : 128
network : 'CNN'
optimizer : 'SGD'
loss_func : 'BinaryCrossentropy'
n_thread : 48
log_verbosity : 1
